FROM ubuntu:20.04
ARG release_version=LATEST_EXZO_RELEASE
RUN apt-get -y update && apt-get -y install libssl-dev libudev-dev curl
RUN curl -sSf https://raw.githubusercontent.com/ExzoNetwork/Exzo-Network-Blockchain/develop/install/exzo-install-init.sh | sh -s - LATEST_EXZO_RELEASE
ENV PATH="/root/.local/share/exzo/install/active_release/bin":"$PATH"
COPY entrypoint.sh entrypoint.sh
ENTRYPOINT [ "/usr/bin/sh","-c", "./entrypoint.sh" ]
